_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.5
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
revision:
    value: no_revision_available
