_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
                - 98
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.5
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
        visualize:
            ChemHotpotQARetrieval_bar_plot:
                panel_config:
                    fieldSettings:
                        label: Metric
                        value: Score
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: ChemHotpotQARetrieval Performance
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: ChemHotpotQARetrieval_bar_plot_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            ChemNQRetrieval_bar_plot:
                panel_config:
                    fieldSettings:
                        label: Metric
                        value: Score
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: ChemNQRetrieval Performance
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: ChemNQRetrieval_bar_plot_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            CoconutRetrieval_bar_plot:
                panel_config:
                    fieldSettings:
                        label: Metric
                        value: Score
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: CoconutRetrieval Performance
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: CoconutRetrieval_bar_plot_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
revision:
    value: ab10c1a7f42e74530fe7ae5be82e6d4f11a719eb
